### ISSUE TITLE
Storybook 6.3.6 + Angular

### ISSUE THREAD

**Issue by JosefBredereck** [criol/storybook-addon-multi-theme#2]
Hello there 👋🏼,

Does this addon work with the latest version of the storybook, and can I use it with storybook angular?

**Comment by clbagrat** [comment]
Hi, unfortunately it isn't possible at the moment, due to the peerDependency on react.
I mean, you can add react to your devDependency object, but I guess your coworkers wouldn't appreciate that 😆
